config/routes.rb
Rails.application.routes.draw do


    resources :cart_items do
      collection do
        resources :charges
      end
    end

  resources :posts
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    end
  devise_scope :user do
    end


  root 'pages#index'
  get 'admindashboard', to: 'admin_dashboard#index'
  # get 'userdashboard', to: 'pages#user_dashboard'
  get 'addtocart', to: 'cart_items#index'
  get 'shoppingcart', to: 'user_dashboard#shopping_cart'

  get 'contact', to: "contact#index"
  post 'contact', to: "contact#mail"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_footer.html.erb
<div class="footer navbar-fixed-bottom">
<div class="container">
  <a href="/contact"> <h3>Contact Us </h3></a>


<div class="fb-share-button" data-href="https://localhost:3000" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Flocalhost%3A3000%2F&amp;src=sdkpreparse">Share</a></div>
</div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">

      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/posts">Gallery</a></li>
        <li class="divider"></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
        <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
        <%= submit_tag "Search" %>
        <% end %> </form>
      </ul>

      <ul class="nav navbar-nav navbar-right">
         <li>  <% if user_signed_in? %>
             <a href="/cart_items">
               <span class="fa fa-shopping-cart fa-2x" aria-hidden="true"></span>
                <%= @cart_items.size %>
             </a>
           <% end %></li>
         <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
           <ul class="dropdown-menu">
             <% if user_signed_in? %>
                  <li>
                    <%= link_to('Admin Profile', admindashboard_path) if current_user.admin? %>
                  </li>
                   <li>
                     <%= link_to('Edit Account', edit_user_registration_path) %>
                   </li>
                 <% end %>
               <li role="separator" class="divider"></li>
                 <% if user_signed_in? %>
                   <li>
                     <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                   </li>
                 <% else %>
                   <li>
                     <%= link_to('Login', new_user_session_path)  %>
                   </li>
                   <li>
                     <%= link_to('Register', new_user_registration_path)  %>
                   </li>
                 <% end %></li>

           </ul>
         </li>
       </ul>

    </div>
</nav>

app/views/partials/_stripe.html.erb
<%= form_tag charges_path(@cart_items = current_user.cart_items) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Checkout items"
          data-amount="<%= @total * 100 %>"

          data-locale="auto"></script>
<% end %>