config/routes.rb
Rails.application.routes.draw do


    resources :cart_items do
      collection do
        resources :charges
      end
    end

  resources :posts
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    end
  devise_scope :user do
    end


  root 'pages#index'
  get 'admindashboard', to: 'admin_dashboard#index'
  # get 'userdashboard', to: 'pages#user_dashboard'
  get 'addtocart', to: 'cart_items#index'
  get 'shoppingcart', to: 'user_dashboard#shopping_cart'

  get 'contact', to: "contact#index"
  post 'contact', to: "contact#mail"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy]




  # GET /cart_items
  # GET /cart_items.json
  def index
  #  @cart_items = CartItem.all
    @cart_items = current_user.cart_items
    @total = current_user.cart_items.sum {|i| i.post.price}

  end

  # GET /cart_items/1
  # GET /cart_items/1.json
  def show
    @cart_items = current_user.cart_items
  end

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
    @cart_items = current_user.cart_items
  end

  # GET /cart_items/1/edit
  def edit
  end

  # POST /cart_items
  # POST /cart_items.json
  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.user_id = current_user.id


    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to @cart_item, notice: 'item was successfully saved to cart.' }
        format.json { render :show, status: :created, location: @cart_item }
      else
        format.html { render :new }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cart_items/1
  # PATCH/PUT /cart_items/1.json
  def update
    respond_to do |format|
      if @cart_item.update(cart_item_params)
        format.html { redirect_to @cart_item, notice: 'item was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart_item }
      else
        format.html { render :edit }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1
  # DELETE /cart_items/1.json
  def destroy
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_items_url, notice: 'item was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_item_params
      params.require(:cart_item).permit(:user_id, :post_id)
    end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_form.html.erb
<%= form_for(cart_item) do |f| %>
  <% if cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% cart_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
<% if params[:post_id].present? %>
  <%= f.hidden_field :post_id, value: params[:post_id] %>
<% end %>
</div>

  <div class="actions">
    <%= f.submit "Yes, please", class: "btn-black"%>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<h1>Editing Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<p id="notice"><%= notice %></p>

<div class="shopping-cart">

  <div class = "container">
  <div class="title-box">
    <h1>Your shopping cart</h1>
  </div>
<div class="cart-content">
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Artwork</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><div class="img">  <%= image_tag cart_item.post.image.url (:thumb) %> </div></td>
        <td><%= cart_item.post.title %></td>
        <td><%= number_to_currency(cart_item.post.price) %></td>
        <td><%= link_to 'Remove from cart', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>

    <% end %>



  </tbody>


</table>

<h2> the total amount is : <%=number_to_currency(@total) %> </h2>
<%= render 'partials/stripe' %>

</div>
</div>
</div>

app/views/cart_items/new.html.erb
<div class="add_to_cart_wrapper">
<div class="add_to_cart">
<p>Do you wish to add this item to your cart?</p>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'No, I changed my mind', posts_path, class: "btn-black" %>
</div>
</div>

app/views/cart_items/show.html.erb
<div class="background_item">

<div class="item_show">

<p>thanks for supporting The Creatiev Project!  </p>
<p> do you wish to continue shopping? </p>

<%= link_to 'Yes, take me back', posts_path, class: "btn-black" %>
<br>
<%= link_to "No, I'd like to pay", cart_items_path, class: "btn-black" %>

</div>
</div>