config/routes.rb
Rails.application.routes.draw do


    resources :cart_items do
      collection do
        resources :charges
      end
    end

  resources :posts
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    end
  devise_scope :user do
    end


  root 'pages#index'
  get 'admindashboard', to: 'admin_dashboard#index'
  # get 'userdashboard', to: 'pages#user_dashboard'
  get 'addtocart', to: 'cart_items#index'
  get 'shoppingcart', to: 'user_dashboard#shopping_cart'

  get 'contact', to: "contact#index"
  post 'contact', to: "contact#mail"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :cart_items

  mount_uploader :image, ImageUploader
  validates_presence_of :image, :user_id, :description, presence: true

  def self.search(search)
    where("description LIKE ? OR title LIKE ?", "%#{search}%", "%#{search}%")
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @cart_items = current_user.cart_items
    @posts = Post.all

    @posts = Post.all
     if params[:search]
       @posts = Post.search(params[:search]).order("created_at DESC")
     else
       @posts = Post.all.order('created_at DESC')
     end
   end



  # GET /posts/1
  # GET /posts/1.json
  def show
    @cart_items = current_user.cart_items

  end

  # GET /posts/new
  def new
    @post = Post.new
    @cart_items = current_user.cart_items
  end

  # GET /posts/1/edit
  def edit
    @cart_items = current_user.cart_items
  end

  # POST /posts
  # POST /posts.json
  def create
    
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @cart_items = current_user.cart_items



    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update

    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    authorize @post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :image, :user_id, :post_image, :post_image_cache, :price)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def randomized_background_image
    images = ["http://res.cloudinary.com/charhagelin/image/upload/v1492827791/wow_pretty_dq4hzv.png", "http://res.cloudinary.com/charhagelin/image/upload/v1492827791/take_money_dvinqc.png", "http://res.cloudinary.com/charhagelin/image/upload/v1492827790/must_have_qd0zga.png"]
    images[rand(images.size)]
  end
end

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
  <%= f.label :price %> <br>
  <%= f.number_field :price %>
</div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :rows => 7, style: 'width:100%;'  %>
  </div>

  <div class="field">
        <%= f.file_field :image %>
        <%= f.hidden_field :image_cache %>
    </div>

  <!-- <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div> -->

  <div class="actions">
    <%= f.submit "submit artwork", class: "btn-black" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="post-index">
<div class="container">



<h1>Gallery</h1>



<%= link_to 'New Post', new_post_path, class: "btn btn-default" %>
<div id="wrapper">
	<div id="columns">

    <% @posts.each do |post| %>
    <div class= "pin">
      <p>
    <div class="img">  <%= image_tag post.image.url (:small) %> </div>
    <hr>
      <h4><strong><%= post.title %></strong></h4>
			<p><strong><%= number_to_currency(post.price) %> </strong></p>
      <br>
      <%= post.description %>
    </p>
      <br>

      <%= link_to 'Show', post, class: "btn btn-show" if current_user.admin? %>

		  <%= link_to 'Edit', edit_post_path(post) if current_user.admin? %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } if current_user.admin?%>
    </div>
    <% end %>

</div>
</div>

</div>
</div>
</div>

app/views/posts/new.html.erb
<div class="new_post_wrapper">
<div class="container">
  <div class="new-post">
<h1>Upload your artwork here</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>
</div>
</div>

app/views/posts/show.html.erb
<div class="random_img">
    <%= image_tag randomized_background_image %>
  </div>
  <div class="container">
  <div class="post-show">
    <p id="notice"><%= notice %></p>


    <%= image_tag @post.image.url (:large) %>

    <hr>
    <p>
      <strong>Title:</strong>
      <%= @post.title %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= number_to_currency(@post.price) %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @post.description %>
    </p>


    <%= link_to 'Add to cart', new_cart_item_path(post_id: @post.id), class: "btn btn-show" %>


    <%= link_to 'Edit', edit_post_path(@post) if current_user.admin? %> |
    <%= link_to 'Back', posts_path, class: "btn btn-default" %>
  </div>
</div>